- name: This is the common task
  debug:
    msg: "Hi, from common tasks execution  - MSG - 1"


- name: This is the common task
  debug:
    msg: "Hi, from common tasks execution  - MSG - 2 {{ item }}"


- name: This is the common task
  debug:
    msg: "Hi, from common tasks execution  - MSG - 3"

# - name: dynamicalling changing the value of OS using set_fact
#   set_fact:
#     os: "Debian"

- name: This is the common task
  debug:
    msg: "Hi, from common tasks execution  - MSG - 4"


# - name: call role-2
#   include_role: 
#     name: role-3